{{- if .Values.frontendApi.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontendApi.serviceAccount.name }}
  namespace: {{ .Values.frontendApi.namespace }}
  {{- with .Values.frontendApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
