account_id: "633630779107"   # The AWS Account ID of the MC
region: "us-east-1"          # The region to deploy the Regional Cluster and Pipeline into
alias: "management01-us-east-1"  # Unique alias for this regional environment